### ISSUE TITLE
Implement User Input Validation

### ISSUE THREAD

**Issue by Tymisko** [FreakyF/Weather-track#22]
As we interact with users, it's crucial to validate the user input to ensure that it's in the expected format and within the expected range. Incorrect user input can lead to bugs, errors, or even security vulnerabilities. In this task, we'll create a user input validation system for our application.

Tasks include:

- **Identify User Input**: Identify all areas in our application where we accept user input. This could include text inputs, file uploads, and form submissions.
- **Define Validation Rules**: For each type of input, define what constitutes valid and invalid input. This could include input length, format, range, etc.
- **Implement Validation**: Implement validation checks for each type of user input in our application. This should happen before any processing or manipulation of the input data.
- **Error Handling**: Ensure that our application handles invalid inputs gracefully. This might involve displaying an error message to the user or requesting them to enter the data again.
- **Testing**: Test the validation system thoroughly with different types of input, including edge cases.

**Acceptance Criteria**:

1. All user input in the application is validated according to defined rules.
2. The application handles invalid inputs gracefully, without crashing or causing bugs.
3. Validation system has been tested and is working as expected.

**Comment by FreakyF** [comment]
# Implement User Input Validation  #22

## Identify User Input
* Right now we only use getUserInput for the getCityNameFromUser method which gets a name of the city from the User as a String. 
* The getUserInput function will also be utilized for selecting options from the menu such as cities with the same name.
## Define Validation Rules
* In the context of city names we should check for:
	* Characters -  The city name should consist only of alphabetic characters, spaces and special characters such as diacritical marks, non-Latin scripts, apostrophes or hyphens and etc.
	* Capitalization - The city names should be case insensitive, meaning if the user enters San Francisco, san francisco or sAN fRanCISCO it will lead to the same city.
	* Whitespaces - Leading and trailing whitespaces should be removed, but internal whitespaces are allowed.
	* Length - The shortest city name in the world is "Å" in Norway, and the longest one is the full name of Bangkok in Thailand which contains 168 characters. We will set the upper limit to 200.
* In the context of options from the menu we should check for:
* Format - the menu input should be only an integer. The user will have the ability to choose a position coresponding to the number he've chosen.
* Range - the menu input range should be within the range of 1 to N. It is highly unlikely that we will have to use a 3-digit number on the menu, but we will leave it just in case.
## Testing
First, we will write unit tests for the input validation, and according to them we will implement UserInputValidation.
## Error handling
For each invalid input we should display an error message to the user, which input validation rule he violated and ask them to enter the data again.
## Implement Validation

Implement User Input Validation #22
Identify User Input
Right now we only use getUserInput for the getCityNameFromUser method which gets a name of the city from the User as a String.
The getUserInput function will also be utilized for selecting options from the menu such as cities with the same name.
Define Validation Rules
In the context of city names we should check for:
Characters - The city name should consist only of alphabetic characters, spaces and special characters such as diacritical marks, non-Latin scripts, apostrophes or hyphens and etc.
Capitalization - The city names should be case insensitive, meaning if the user enters San Francisco, san francisco or sAN fRanCISCO it will lead to the same city.
Whitespaces - Leading and trailing whitespaces should be removed, but internal whitespaces are allowed.
Length - The shortest city name in the world is “Å” in Norway, and the longest one is the full name of Bangkok in Thailand which contains 168 characters. We will set the upper limit to 200.
In the context of options from the menu we should check for:
Format - the menu input should be only an integer. The user will have the ability to choose a position coresponding to the number he’ve chosen.
Range - the menu input range should be within the range of 1 to N. It is highly unlikely that we will have to use a 3-digit number on the menu, but we will leave it just in case.
Testing
First, we will write unit tests for the input validation, and according to them we will implement UserInputValidation.

Error handling
For each invalid input we should display an error message to the user, which input validation rule he violated and ask them to enter the data again.

Implement Validation
Markdown selection 1756 bytes 312 words 19 lines Ln 20, Col 0HTML 1415 characters 296 words 18 paragraphs
