### ISSUE TITLE
Decision Needed: Choosing a Dependency Injection Library for Our Project

### ISSUE THREAD

**Issue by Tymisko** [FreakyF/Weather-track#30]
As we continue to improve our codebase, we have identified a need for implementing dependency injection (DI) in our project. We're not using the Spring framework, so we need to integrate an alternative DI library.

## After researching, we've shortlisted the following five libraries:
| Library | Maintained By | Key Features | Best Use Cases |
|---------|---------------|--------------|----------------|
| Google Guice | Google | Lightweight, Supports method, field, and constructor injection, Integrates well with other Google libraries | General purpose, particularly where performance is a concern |
| Dagger | Google | Compile-time DI, Ensures code correctness via compile-time checks, Lightweight | Android Development, and general purpose where compile-time DI is beneficial |
| PicoContainer | Open Source Community | Minimalistic, Supports constructor, setter, and method injection | Small to medium applications, where simplicity is a priority |
| HK2 | Eclipse Foundation | Lightweight, Dynamic DI, Supports service-based architecture | JavaEE applications, Microservices |
| CDI | Java Community Process (JCP) | Part of Java EE, Integrates well with other Java EE technologies, Supports context and scopes | Enterprise-level JavaEE applications |

Before deciding, we need to consider our specific needs and constraints, such as the size and complexity of our project, performance requirements, and our team's familiarity with these libraries.

## Once we've chosen a library, we will proceed with these steps:
- [x]  Add the library to our project dependencies.
- [x]  Refactor our code to apply dependency injection where appropriate.
- [x]  Thoroughly test all refactored classes to ensure they still function correctly.
- [x]  Document the changes and the DI process in our project documentation.

**Comment by FreakyF** [comment]
The library of our choice will be Google Guice, since We are using Google Json already, and Google Guice is fairly popular.
