### ISSUE TITLE
Setting Up a GitHub Repository

### ISSUE THREAD

**Issue by Tymisko** [FreakyF/Weather-track#8]
We need a central place where we can store, manage, and version control our project's source code. A GitHub repository serves this purpose well. This issue involves creating a new repository on GitHub for our weather console application and setting up the necessary files and configurations.

Here are the tasks that we need to address for this issue:

- **Repository Creation**: Create a new GitHub repository for our project.
- **Readme File**: Add a README.md file to the repository that explains the project, how to run the code, and how to contribute to the project.
- **License**: Decide on a license for our project and add a LICENSE file to the repository.
- **Branch Protection Rules**: Set up branch protection rules to ensure code quality and prevent direct pushes to the main branch.
- **Integration with CI/CD tools**: If we plan to use continuous integration/continuous deployment, set up the necessary configurations.

**Acceptance Criteria**:

1. The GitHub repository is set up and contains the initial codebase, README.md, a LICENSE, and CONTRIBUTING.md files.
2. Branch protection rules are configured correctly.
3. the repository is correctly integrated with our CI/CD tools if applicable.

**Comment by FreakyF** [comment]
Integration with CI/CD tools moved to issue #16.
